site_name: ConfigMap Merging Controller
repo_name: cashapp/cmmc
repo_url: https://github.com/cashapp/cmmc
site_url: https://cashapp.github.io/cmmc/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
  - navigation.sections

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
