# permissions for end users to view mergetargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mergetarget-viewer-role
rules:
- apiGroups:
  - cmmc.cmmc.k8s.cash.app
  resources:
  - mergetargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cmmc.cmmc.k8s.cash.app
  resources:
  - mergetargets/status
  verbs:
  - get
