# permissions for end users to view mergesources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mergesource-viewer-role
rules:
- apiGroups:
  - cmmc.cmmc.k8s.cash.app
  resources:
  - mergesources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cmmc.cmmc.k8s.cash.app
  resources:
  - mergesources/status
  verbs:
  - get
